### ISSUE TITLE
StartChooser: Version check: java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nxs47** [VennMaker/vennmaker-source#13]
[java.base/java.lang.Thread.getStackTrace(Thread.java:1598), gui.ErrorUncaughtExceptionHandler.uncaughtException(ErrorUncaughtExceptionHandler.java:95), java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1053), java.base/java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1048), java.base/java.lang.Thread.dispatchUncaughtException(Thread.java:1993)]
java.lang.StringIndexOutOfBoundsException: begin 2, end 3, length 2
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
	at java.base/java.lang.String.substring(String.java:1902)
	at gui.StartChooser.(StartChooser.java:292)
	at gui.VennMaker.main(VennMaker.java:2697)

VennMaker Version:2.0.2

**Comment by nxs47** [comment]
see commit https://github.com/VennMaker/vennmaker-source/commit/0c3f916ac4f00fd5e84f2f3eb87819fc757e942a
